### ISSUE TITLE
Hide sidebar works for lhs sidebar only

### ISSUE THREAD

**Issue by MacDisein** [wickedest/Mergely#77] opened 2018-04-12 18:01 UTC
If I set „sidebar: false“ only the sidebar on the left hand side editor disappears.

**Comment by wickedest** [comment] 2018-04-12 20:07
It sounds like you have some other kind of css issue.  I cannot reproduce.  Try reducing the problem, e.g. load one of the examples and disable the sidebar.

**Comment by wickedest** [comment] 2018-04-12 20:24
It hides both left and right sidebar:
![image](https://user-images.githubusercontent.com/871639/38702196-e2ad585c-3e97-11e8-984d-1e08d36cbea7.png)

Note that it does not hide _scrollbar_.

**Comment by MacDisein** [comment] 2018-04-12 20:32
Hmmm, not here, tried it with different browsers on different machines.
![b54c06f8-0257-43f1-b0a4-1ed64807cf94](https://user-images.githubusercontent.com/8401876/38702607-59381da0-3ea1-11e8-93df-1970fa44a0af.png)

**Comment by wickedest** [comment] 2018-04-12 20:44
ipad?  Safari?  y, could be something like that.

**Comment by MacDisein** [comment] 2018-04-13 06:32
The screenshot is from an iPad with Safari browser, but as described above, I can reproduce the problem with different browsers on different operating systems.
After playing around with the jsfiddle demo a bit - I think I know what the reason is, the sidebar is not hidden if the option is set via "onLoad", if you change the option later (e.g. by clicking the button "Toggle line break") - the right sidebar disappears.

Steps to reproduce:
1. Call the jsfiddle example => both sidebars are visible
2. Add "sidebar: false," at line 17 in the "js" pane
3. Click "Run" at the top left corner of the jsfiddle window => only the left sidebar becomes invisible
4. Click the "Toggle line wrapping" button in the "result" pane => the right sidebar dissapears

**Comment by MacDisein** [comment] 2018-04-16 09:34
As a workaround I do not set "sidebar" while creating the mergely object. I get and set the options later and then all sidebars are hidden as expected.

var options = $('#mergely').mergely('options');
options.sidebar = false;
$('#mergely').mergely('options', options);

**Comment by wickedest** [comment] 2018-05-26 20:10
Fixed in 4.0.2

**Closed by wickedest** 2018-05-26 20:10 UTC
